### ISSUE TITLE
AWS ELB with https

### ISSUE THREAD

**Issue by shraykay** [yuvipanda/jupyterhub-nginx-chp#11]
Using your "simplest" manifest under https://github.com/yuvipanda/jupyterhub-simplest-k8s and enabling SSL at the AWS load balancer causes the "loading kernel" step after successfully launching a pod to fail. This seems to be a proxy routing issue but my nginx-fu is not up to par. Would you have any ideas?

```
kubectl logs hub-proxy-deployment-1347898349-beane | grep 400

10.2.106.0 - - [05/Oct/2016:19:20:17 +0000] "GET /user/s/api/kernels/d74f27c7-2bbb-40fa-b44d-9602713c318f/channels?session_id=232532B3186A427FA17CC644623763BC HTTP/1.1" 400 34 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
```

![screenshot](https://i.imgur.com/cn3Z6K9.png)

**Comment by yuvipanda** [comment]
Do you see the pod running successfully? What's in the pod's logs? Also can you try the persistent-hubdb configuration instead? And how did you setup k8s?

**Comment by shraykay** [comment]
I figured it out -- AWS ELB was set to HTTPS and not SSL with TCP instead. This solved the problem. Thanks!
